import { Offer } from '@/store/slices/offersSlice';

export const initialPopularBrands = [
  { id: '1', name: 'Amazon', icon: 'a', deals: 24, color: '#FF9900' },
  { id: '2', name: 'Apple', icon: '🍎', deals: 12, color: '#000000' },
  { id: '3', name: 'Nike', icon: '✓', deals: 18, color: '#000000' },
  { id: '4', name: 'Spotify', icon: '♪', deals: 9, color: '#1DB954' },
  { id: '5', name: 'Uber', icon: 'U', deals: 15, color: '#000000' },
];

export const initialTrendingOffers: Offer[] = [
  {
    id: '1',
    brand: 'Nykaa',
    brandIcon: '🌸',
    brandColor: '#E91E63',
    title: 'Flat 50% Off at Nykaa',
    description: 'Valid on all beauty products. Limited time offer.',
    timeLeft: '2d left',
    badge: '50% OFF',
    badgeColor: '#FF4444',
    isTrending: true,
    isVerified: true,
  },
  {
    id: '2',
    brand: 'PayPal',
    brandIcon: 'P',
    brandColor: '#0070BA',
    title: '$10 Cashback',
    description: 'New user offer. Valid on first transaction.',
    timeLeft: '5d left',
    badge: 'CASHBACK',
    badgeColor: '#50C878',
    isTrending: true,
    isVerified: true,
  },
  {
    id: '3',
    brand: 'Netflix',
    brandIcon: 'N',
    brandColor: '#E50914',
    title: '1 Month Free Trial',
    description: 'Watch unlimited movies and TV shows.',
    timeLeft: '3d left',
    badge: 'FREE',
    badgeColor: '#50C878',
    isTrending: true,
    isVerified: true,
  },
  {
    id: '4',
    brand: 'Starbucks',
    brandIcon: '☕',
    brandColor: '#00704A',
    title: 'Buy 1 Get 1 Free',
    description: 'On all holiday drinks. Valid until Dec 31st.',
    timeLeft: '4d left',
    badge: 'BOGO',
    badgeColor: '#FFA500',
    isTrending: true,
    isVerified: true,
  },
  {
    id: '5',
    brand: 'Amazon',
    brandIcon: 'a',
    brandColor: '#FF9900',
    title: 'Up to 70% Off Electronics',
    description: 'Year-end sale on top mobile brands.',
    timeLeft: '1d left',
    badge: '70% OFF',
    badgeColor: '#FF4444',
    isTrending: true,
    isVerified: true,
  },
];

export const initialAllOffers: Offer[] = [
  {
    id: '1',
    brand: 'LinkedIn',
    brandIcon: 'in',
    brandColor: '#0077B5',
    title: '50% Off Premium',
    badge: '50% OFF',
    badgeColor: '#FF4444',
    category: 'Professional',
    expiryDate: '2024-12-31',
    promoCode: 'LINKEDIN50',
    isVerified: true,
  },
  {
    id: '2',
    brand: "McDonald's",
    brandIcon: '🍔',
    brandColor: '#FFC72C',
    title: 'Buy 1 Get 1 Free',
    badge: 'BOGO',
    badgeColor: '#FF4444',
    category: 'Food & Dining',
    expiryDate: '2024-11-30',
    promoCode: 'MCDBOGO',
    isVerified: true,
  },
  {
    id: '3',
    brand: 'Twitch',
    brandIcon: '🎮',
    brandColor: '#9146FF',
    title: '30-Day Free Trial',
    badge: 'FREE',
    badgeColor: '#50C878',
    category: 'Entertainment',
    expiryDate: '2024-12-15',
    promoCode: 'TWITCH30',
    isVerified: true,
  },
  {
    id: '4',
    brand: 'FitPass',
    brandIcon: '💪',
    brandColor: '#4CAF50',
    title: '70% Off Annual Plan',
    badge: '70% OFF',
    badgeColor: '#FF4444',
    category: 'Sports',
    expiryDate: '2024-11-20',
    promoCode: 'FITPASS70',
    isVerified: true,
  },
  {
    id: '5',
    brand: 'YouTube',
    brandIcon: '▶',
    brandColor: '#FF0000',
    title: '3 Months Premium',
    badge: 'FREE',
    badgeColor: '#50C878',
    category: 'Entertainment',
    expiryDate: '2024-12-25',
    promoCode: 'YOUTUBE3M',
    isVerified: true,
  },
  {
    id: '6',
    brand: 'Dropbox',
    brandIcon: '📦',
    brandColor: '#0061FF',
    title: '2TB for $9.99/mo',
    badge: '60% OFF',
    badgeColor: '#FF4444',
    category: 'Technology',
    expiryDate: '2024-12-10',
    promoCode: 'DROPBOX60',
    isVerified: true,
  },
];

export const initialCategories = [
  { id: '1', name: 'Electronics', icon: '📱', count: 24, color: '#4A90E2' },
  { id: '2', name: 'Fashion', icon: '👕', count: 18, color: '#E94B3C' },
  { id: '3', name: 'Home & Living', icon: '🏠', count: 15, color: '#50C878' },
  { id: '4', name: 'Sports', icon: '⚽', count: 12, color: '#FF6B35' },
  { id: '5', name: 'Beauty', icon: '💄', count: 20, color: '#FF69B4' },
  { id: '6', name: 'Food & Dining', icon: '🍔', count: 16, color: '#FFA500' },
  { id: '7', name: 'Books', icon: '📚', count: 10, color: '#9B59B6' },
  { id: '8', name: 'Toys & Games', icon: '🎮', count: 14, color: '#1ABC9C' },
];
